import unittest
from Jellybeans.Algos import reachability, counting_components, topological_sort
from Jellybeans.Structures import Graph

class test_GraphAlgos(unittest.TestCase):

    def test_reachability1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(4)
        g.add_vertex(9)
        g.add_edge(1, 4, 5)
        g.add_edge(4, 9, 6)
        g.add_edge(9, 1, 7)
        reachable, path = reachability(g, 4, 1)
        self.assertTrue(reachable)
        self.assertEqual(path, (4, 9, 1))

    def test_reachability2(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(0, 1, 5)
        g.add_edge(0, 2, 6)
        g.add_edge(1, 2, 7)
        g.add_edge(1, 3, 8)
        g.add_edge(2, 3, 9)
        reachable, path = reachability(g, 0, 3)
        self.assertTrue(reachable)
        self.assertEqual(path, (0, 1, 3))

    def test_reachability3(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(0, 1, 5)
        g.add_edge(0, 2, 6)
        g.add_edge(1, 2, 7)
        g.add_edge(1, 3, 8)
        g.add_edge(2, 3, 9)
        reachable, path = reachability(g, 3, 0)
        self.assertFalse(reachable)
        self.assertIsNone(path)

    def test_components1(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        res = counting_components(g)
        self.assertEqual(res, 4)

    def test_components2(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_bidirected_edge(0, 1, (5, -5))
        g.add_bidirected_edge(0, 2, (6, -6))
        g.add_bidirected_edge(1, 2, (7, -7))
        g.add_bidirected_edge(1, 3, (8, -8))
        g.add_bidirected_edge(2, 3, (9, -9))
        res = counting_components(g)
        self.assertEqual(res, 1)

    def test_components3(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(6)
        g.add_vertex(7)
        g.add_bidirected_edge(0, 1, (5, -5))
        g.add_bidirected_edge(0, 2, (5, -5))
        g.add_bidirected_edge(1, 2, (5, -5))
        g.add_bidirected_edge(1, 3, (5, -5))
        g.add_bidirected_edge(2, 3, (5, -5))
        g.add_bidirected_edge(3, 4, (5, -5))
        g.add_bidirected_edge(2, 5, (5, -5))
        g.add_bidirected_edge(7, 6, (5, -5))
        res = counting_components(g)
        self.assertEqual(res, 2)

    def test_toposort1(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        res = topological_sort(g)
        self.assertEqual(res, [0, 1, 2, 3])

    def test_toposort2(self):
            g = Graph()
            g.add_vertex(0)
            g.add_vertex(1)
            g.add_vertex(2)
            g.add_vertex(3)
            g.add_edge(3, 2)
            g.add_edge(2, 1)
            g.add_edge(1, 0)
            res = topological_sort(g)
            self.assertEqual(res, [3, 2, 1, 0])
    
    def test_toposort3(self):
            g = Graph()
            g.add_vertex(0)
            g.add_vertex(1)
            g.add_vertex(2)
            g.add_vertex(3)
            g.add_vertex(4)
            g.add_edge(0, 1)
            g.add_edge(0, 2)
            g.add_edge(0, 3)
            g.add_edge(1, 3)
            g.add_edge(1, 4)
            g.add_edge(2, 4)
            g.add_edge(3, 4)
            res = topological_sort(g)
            self.assertEqual(res, [0, 1, 2, 3, 4])
