import unittest
from jellybeans.structures import Graph
from jellybeans.exceptions.graph_property import _GraphProperty

class test_Graph(unittest.TestCase):
    
    def test_add_replicated_node(self):
        g = Graph()
        g.add_vertex(1)
        with self.assertRaises(_GraphProperty):
            g.add_vertex(1)

    def test_add_unreplicated_node(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        self.assertEqual(g.num_vertices(), 3)
        self.assertEqual(g.list_vertices(), [1,2,3])

    def test_add_edge_with_missing_node(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        with self.assertRaises(_GraphProperty):
            g.add_edge(1, 4, weight=3)
        with self.assertRaises(_GraphProperty):
            g.add_edge(vFrom=5, vTo=6, weight=10)

    def test_add_replicated_edge(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_edge(1, 2, weight=3)
        with self.assertRaises(_GraphProperty):
            g.add_edge(1, 2, weight=3)
        with self.assertRaises(_GraphProperty):
            g.add_edge(vFrom=1, vTo=2, weight=4)

    def test_add_edge_with_replicated_node(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        with self.assertRaises(_GraphProperty):
            g.add_edge(1,1)

    def test_add_unreplicated_edge(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(1, 3, 6)
        self.assertEqual(g.edges_of(1), [(2, 5), (3, 6)])

    def test_neighbours(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(1, 3, 6)
        self.assertEqual(g.neighbours_of(1), [2, 3])
        self.assertEqual(g.neighbours_of(2), [])

    def test_neighbours_length(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(1, 3, 6)
        self.assertEqual(g.num_neighbours(1), 2)
        self.assertEqual(g.num_neighbours(2), 0)

    def test_reachability(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        self.assertEqual(g.can_reach(2), [1,3])
        self.assertEqual(g.can_reach(1), [])
        self.assertEqual(g.can_reach(3), [])

    def test_delete_edge(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.delete_edge([1,2])
        self.assertEqual(g.can_reach(2), [3])
        self.assertEqual(g.can_reach(1), [])
        self.assertEqual(g.can_reach(3), [])

    def test_delete_repeated_edge(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.delete_edge([1,2])
        with self.assertRaises(_GraphProperty):
            g.delete_edge([1,2])

    def test_delete_node(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.delete_vertex(2)
        self.assertEqual(g.can_reach(1), [])
        self.assertEqual(g.can_reach(3), [])
        self.assertEqual(g.list_vertices(), [1, 3])

    def test_delete_repeated_node(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.delete_vertex(2)
        with self.assertRaises(_GraphProperty):
            g.delete_vertex(2)

    def test_edge_list1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        self.assertEqual(g.to_edgeList(), [(1, 2, 5), (1, 3, 7), (3, 2, 6)])

    def test_edge_list2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        g.delete_vertex(2)
        self.assertEqual(g.to_edgeList(), [(1, 3, 7)])

    def test_adj_list1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        self.assertEqual(g.to_adjList(), {1: [(2, 5), (3, 7)], 2: [], 3: [(2, 6)]})

    def test_adj_list2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        g.delete_vertex(2)
        self.assertEqual(g.to_adjList(), {1: [(3, 7)], 3: []})

    def test_adj_Matrix1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        self.assertEqual(g.to_adjMatrix()[1], [[0, 5, 7], [0, 0, 0], [0, 6, 0]])

    def test_adj_Matrix2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        g.delete_vertex(2)
        self.assertEqual(g.to_adjMatrix()[1], [[0, 7], [0, 0]])

    def test_update_weight(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(3, 2, 6)
        g.add_edge(1, 3, 7)
        g.update_edge_weight([1, 3], 123)
        self.assertEqual(g.to_adjMatrix()[1], [[0, 5, 123], [0, 0, 0], [0, 6, 0]])

    def test_is_tree1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_bidirected_edge(1, 2, (1,1))
        g.add_bidirected_edge(2, 3, (1,1))
        self.assertTrue(g.is_tree())

    def test_is_tree2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_bidirected_edge(1, 2, (1,1))
        g.add_bidirected_edge(2, 3, (1,1))
        g.add_bidirected_edge(3, 1, (1,1))
        self.assertFalse(g.is_tree())

    def test_is_tree3(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_bidirected_edge(1, 2, (1,1))
        g.add_bidirected_edge(2, 3, (1,1))
        g.add_bidirected_edge(3, 4, (1,1))
        g.add_bidirected_edge(4, 5, (1,1))
        g.add_bidirected_edge(5, 3, (1,1))
        self.assertFalse(g.is_tree())

    def test_is_tree4(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_bidirected_edge(1, 2, (1,1))
        g.add_bidirected_edge(2, 3, (1,1))
        self.assertFalse(g.is_tree())

    def test_is_tree5(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2)
        g.add_edge(2, 3)
        g.add_edge(3, 1)
        self.assertFalse(g.is_tree())

    def test_is_tree6(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_edge(1, 2)
        g.add_edge(2, 3)
        g.add_edge(3, 1)
        self.assertFalse(g.is_tree())

    def test_is_tree7(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_edge(1, 2)
        g.add_edge(2, 3)
        g.add_edge(3, 4)
        self.assertFalse(g.is_tree())

    def test_is_tree8(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_edge(1, 2)
        g.add_edge(1, 3)
        g.add_edge(1, 4)
        g.add_edge(4, 5)
        self.assertFalse(g.is_tree())

    def test_is_tree9(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2)
        g.add_edge(1, 3)
        g.add_edge(2, 3)
        self.assertFalse(g.is_tree())

    def test_is_tree10(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_edge(4, 1)
        g.add_edge(1, 2)
        g.add_edge(1, 3)
        g.add_edge(2, 3)
        self.assertFalse(g.is_tree())

    def test_is_tree11(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_bidirected_edge(1, 2, (1, 1))
        g.add_bidirected_edge(1, 3, (1, 1))
        g.add_bidirected_edge(1, 4, (1, 1))
        g.add_bidirected_edge(4, 5, (1, 1))
        self.assertTrue(g.is_tree())

    def test_is_tree12(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_bidirected_edge(1, 2)
        g.add_bidirected_edge(2, 3)
        g.add_bidirected_edge(3, 1)
        self.assertFalse(g.is_tree())

    def test_is_unweighted1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_edge(1, 2)
        g.add_edge(1, 3)
        g.add_edge(1, 4)
        g.add_edge(4, 5)
        self.assertTrue(g.is_unweighted())

    def test_is_unweighted2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_edge(1, 2, 10)
        g.add_edge(1, 3, 3)
        g.add_edge(1, 4, 7)
        g.add_edge(4, 5, 5)
        self.assertFalse(g.is_unweighted())

    def test_is_unweighted3(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_bidirected_edge(1, 2, (1,1))
        g.add_bidirected_edge(2, 3, (1,1))
        self.assertTrue(g.is_unweighted())

    def test_is_unweighted4(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_bidirected_edge(1, 2, (123,123))
        self.assertTrue(g.is_unweighted())

    def test_is_unweighted5(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_bidirected_edge(1, 2, (123,124))
        self.assertFalse(g.is_unweighted())

    def test_is_positve1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(1, 3, 0)
        g.add_edge(2, 3, 0)
        self.assertTrue(g.is_positive())

    def test_is_positve2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(1, 3, 0)
        g.add_edge(2, 3, -1)
        self.assertFalse(g.is_positive())

    def test_is_positve3(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2, 5)
        g.add_edge(1, 3, -1)
        g.add_edge(2, 3, 5)
        self.assertFalse(g.is_positive())

    def test_is_positve4(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(6)
        g.add_vertex(7)
        g.add_vertex(8)
        g.add_vertex(9)
        g.add_edge(0, 1, 4)
        g.add_edge(0, 2, 4)
        g.add_edge(1, 3, 4)
        g.add_edge(1, 4, 4)
        g.add_edge(2, 1, 4)
        g.add_edge(2, 5, 4)
        g.add_edge(3, 6, 4)
        g.add_edge(3, 7, 4)
        g.add_edge(4, 2, 2)
        g.add_edge(4, 3, 4)
        g.add_edge(4, 7, 4)
        g.add_edge(4, 8, 4)
        g.add_edge(5, 4, 4)
        g.add_edge(5, 8, 4)
        g.add_edge(6, 7, 4)
        g.add_edge(7, 8, 4)
        g.add_edge(8, 9, 4)
        g.add_edge(9, 5, 4)
        self.assertTrue(g.is_positive())

    def test_is_positve5(self):
        g = Graph()
        g.add_vertex(0)
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(6)
        g.add_vertex(7)
        g.add_vertex(8)
        g.add_vertex(9)
        g.add_edge(0, 1, 4)
        g.add_edge(0, 2, 4)
        g.add_edge(1, 3, 4)
        g.add_edge(1, 4, 4)
        g.add_edge(2, 1, 4)
        g.add_edge(2, 5, 4)
        g.add_edge(3, 6, 4)
        g.add_edge(3, 7, 4)
        g.add_edge(4, 2, 2)
        g.add_edge(4, 3, 4)
        g.add_edge(4, 7, 4)
        g.add_edge(4, 8, 4)
        g.add_edge(5, 4, -4)
        g.add_edge(5, 8, 4)
        g.add_edge(6, 7, 4)
        g.add_edge(7, 8, 4)
        g.add_edge(8, 9, 4)
        g.add_edge(9, 5, 4)
        self.assertFalse(g.is_positive())

    def test_is_dag1(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_bidirected_edge(1, 2, (1,1))
        self.assertFalse(g.is_dag())

    def test_is_dag2(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_bidirected_edge(1, 2, (1,1))
        self.assertFalse(g.is_dag())

    def test_is_dag3(self):
        g = Graph()
        g.add_vertex(1)
        self.assertTrue(g.is_dag())

    def test_is_dag4(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_bidirected_edge(1, 2, (1,1))
        g.add_bidirected_edge(2, 3, (1,1))
        g.add_bidirected_edge(3, 4, (1,1))
        g.add_bidirected_edge(4, 5, (1,1))
        g.add_bidirected_edge(5, 3, (1,1))
        self.assertFalse(g.is_dag())

    def test_is_dag5(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_edge(1, 2)
        g.add_edge(1, 3)
        g.add_edge(2, 3)
        self.assertTrue(g.is_dag())
    
    def test_is_dag6(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_edge(4, 1)
        g.add_edge(1, 2)
        g.add_edge(1, 3)
        g.add_edge(2, 3)
        self.assertTrue(g.is_dag())

    def test_is_dag7(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(0)
        g.add_edge(5, 0)
        g.add_edge(4, 0)
        g.add_edge(5, 2)
        g.add_edge(4, 1)
        g.add_edge(2, 3)
        g.add_edge(3, 1)
        self.assertTrue(g.is_dag())

    def test_is_dag8(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(6)
        g.add_vertex(7)
        g.add_vertex(0)
        g.add_edge(7, 5)
        g.add_edge(7, 6)
        g.add_edge(5, 4)
        g.add_edge(6, 4)
        g.add_edge(6, 3)
        g.add_edge(5, 2)
        g.add_edge(2, 1)
        g.add_edge(3, 1)
        g.add_edge(1, 0)
        self.assertTrue(g.is_dag())

    def test_is_dag9(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(6)
        g.add_vertex(7)
        g.add_vertex(0)
        g.add_edge(5, 7)
        g.add_edge(7, 6)
        g.add_edge(4, 5)
        g.add_edge(6, 4)
        g.add_edge(6, 3)
        g.add_edge(5, 2)
        g.add_edge(2, 1)
        g.add_edge(3, 1)
        g.add_edge(1, 0)
        self.assertFalse(g.is_dag())

    def test_is_dag10(self):
        g = Graph()
        g.add_vertex(1)
        g.add_vertex(2)
        g.add_vertex(3)
        g.add_vertex(4)
        g.add_vertex(5)
        g.add_vertex(6)
        g.add_edge(1, 2)
        g.add_edge(1, 4)
        g.add_edge(2, 3)
        g.add_edge(4, 2)
        g.add_edge(4, 6)
        g.add_edge(4, 5)
        g.add_edge(5, 6)
        self.assertTrue(g.is_dag())